const cmdContainer = document.getElementById('cmdContainer');

// Lista de comandos de hacker
const hackerCommands = [
    "decrypt firewall",
    "hack mainframe",
    "bypass security",
    "initiate cyberattack",
    "extract data",
    "decrypt firewall",
    "hack mainframe",
    "bypass security",
    "initiate cyberattack",
    "extract data",
    "crack password",
    "exploit vulnerability",
    "plant malware",
    "execute denial-of-service attack",
    "encrypt files",
    "analyze network traffic",
    "hack into government database",
    "steal cryptocurrency",
    "disguise identity",
    "initiate ransomware attack",
    "deploy phishing scam",
    "create backdoor",
    "breach firewall",
    "override system permissions",
    "inject code",
    "launch keylogger",
    "hack satellite system",
    "manipulate financial records",
    "spread computer virus",
    "hack into military server",
    "obfuscate traces",
    "initiate social engineering attack",
    "breach biometric security",
    "plant Trojan horse",
    "compromise IoT devices",
    "exploit zero-day vulnerability",
    "intercept communications",
    "initiate cyber espionage",
    "launch cyberwarfare operation",
    "hack into nuclear launch system",
    "access classified information",
    "disrupt power grid",
    "execute man-in-the-middle attack",
    "plant logic bomb",
    "exploit weak encryption",
    "hack autonomous vehicles",
    "infiltrate dark web",
    "initiate cyber extortion",
    "breach air traffic control system",
    "deploy steganography technique",
    "hack into election system",
    "steal intellectual property",
    "initiate cyber sabotage",
    "breach cryptocurrency exchange",
    "launch botnet attack",
    "exploit software vulnerability",
    "hack into financial institution",
    "disrupt online services",
    "initiate cyber terrorism",
    "compromise cloud infrastructure",
    "hack into quantum computer",
    "plant rootkit",
    "initiate cyber blackmail",
    "deploy spoofing attack",
    "bypass biometric authentication",
    "exploit RFID vulnerability",
    "hack into autonomous drones",
    "breach satellite communication",
    "access government secrets",
    "disrupt critical infrastructure",
    "initiate cyber stalking",
    "compromise industrial control system",
    "deploy ransomware-as-a-service",
    "exploit AI vulnerability",
    "hack into smart city system",
    "breach military defense network",
    "access confidential documents",
    "disrupt global financial system",
    "initiate cyber fraud",
    "compromise supply chain",
    "deploy distributed denial-of-service attack",
    "exploit blockchain vulnerability",
    "hack into healthcare database",
    "breach space agency network",
    "access corporate trade secrets",
    "disrupt telecommunication network",
    "initiate cyberbullying",
    "compromise election infrastructure",
    "deploy malware-as-a-service",
    "exploit quantum encryption",
    "hack into autonomous weapons system",
    "breach nuclear facility network",
    "access sensitive personal information",
    "disrupt transportation system",
    "initiate cyber stalking",
    "compromise public utility system",
    "deploy phishing-as-a-service",
    "exploit smart home vulnerability",
    "hack into financial trading system",
    "breach cryptocurrency wallet",
    "access classified military plans",
    "disrupt emergency response system",
    "initiate cyber espionage",
    "compromise satellite navigation system",
    "deploy spyware-as-a-service",
    "exploit edge computing vulnerability",
    "hack into autonomous vehicles network",
    "breach classified government network",
    "access intellectual property",
    "disrupt global supply chain",
    "initiate cyber harassment",
    "compromise autonomous drone system",
    "deploy ransomware-as-a-service",
    "exploit cloud computing vulnerability",
    "hack into quantum encryption",
    "breach AI system network",
    "access government defense secrets",
    "disrupt smart city infrastructure",
    "initiate cyber terrorism",
    "compromise autonomous vehicle system",
    "deploy malware-as-a-service",
    "exploit blockchain vulnerability",
    "hack into healthcare database",
    "breach space agency network",
    "access corporate trade secrets",
    "disrupt telecommunication network",
    "initiate cyberbullying",
    "compromise election infrastructure",
    "deploy phishing-as-a-service",
    "exploit smart home vulnerability",
    "hack into financial trading system",
    "breach cryptocurrency wallet",
    "access classified military plans",
    "disrupt emergency response system",
    "initiate cyber espionage",
    "compromise satellite navigation system",
    "deploy spyware-as-a-service",
    "exploit edge computing vulnerability",
    "hack into autonomous vehicles network",
    "breach classified government network",
    "access intellectual property",
    "disrupt global supply chain",
    "initiate cyber harassment",
    "compromise autonomous drone system",
    "deploy ransomware-as-a-service",
    "exploit cloud computing vulnerability",
    "hack into quantum encryption",
    "breach AI system network",
    "access government defense secrets",
    "disrupt smart city infrastructure",
    "initiate cyber terrorism",
    "compromise autonomous vehicle system",
    "deploy malware-as-a-service",
    "exploit blockchain vulnerability",
    "hack into healthcare database",
    "breach space agency network",
    "access corporate trade secrets",
    "disrupt telecommunication network",
    "initiate cyberbullying",
    "compromise election infrastructure",
    "deploy phishing-as-a-service",
    "exploit smart home vulnerability",
    "hack into financial trading system",
    "breach cryptocurrency wallet",
    "access classified military plans",
    "disrupt emergency response system",
    "initiate cyber espionage",
    "compromise satellite navigation system",
    "deploy spyware-as-a-service",
    "exploit edge computing vulnerability",
    "hack into autonomous vehicles network",
    "breach classified government network",
    "access intellectual property",
    "disrupt global supply chain",
    "initiate cyber harassment",
    "compromise autonomous drone system",
    "deploy ransomware-as-a-service",
    "exploit cloud computing vulnerability",
    "hack into quantum encryption",
    "breach AI system network",
    "access government defense secrets",
    "disrupt smart city infrastructure",
    "initiate cyber terrorism",
    "compromise autonomous vehicle system",
    "deploy malware-as-a-service",
    "exploit blockchain vulnerability",
    "hack into healthcare database",
    "breach space agency network",
    "access corporate trade secrets",
    "disrupt telecommunication network",
    "initiate cyberbullying",
    "compromise election infrastructure",
    "deploy phishing-as-a-service",
    "exploit smart home vulnerability",
    "hack into financial trading system",
    "breach cryptocurrency wallet",
    "access classified military plans",
    "disrupt emergency response system",
    "initiate cyber espionage",
    "compromise satellite navigation system",
    "deploy spyware-as-a-service",
    "exploit edge computing vulnerability",
    "hack into autonomous vehicles network",
    "breach classified government network",
    "access intellectual property",
    "disrupt global supply chain",
    "initiate cyber harassment",
    "compromise autonomous drone system"
];

function executeCommands() {
    let index = 0;

    function executeCommand() {
        if (index >= hackerCommands.length) {
            index = 0;
        }

        const command = hackerCommands[index];
        const commandElement = document.createElement('div');
        commandElement.textContent = `$ ${command}`;
        cmdContainer.appendChild(commandElement);
        cmdContainer.scrollTop = cmdContainer.scrollHeight;

        index++;
        setTimeout(executeCommand, 150);
    }

    executeCommand(); // Inicia a execução dos comandos
}

executeCommands(); // Chama a função para iniciar a execução dos comandos
